### ISSUE TITLE
I dont get how to config subcommands-hotkeys

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_runner#11]
it's hotkeys from build-systems? authors already set them? 

Also-- can we make more lite `__init__` to speedup loading? i have 18 ms for plugin.

**Comment by halfbrained** [comment]
Added [description](https://github.com/halfbrained/cuda_runner/commit/e65cf376af2f361705df9e5aacd0f5efa8c1f3db#diff-f5d8cd29c638d89e2c227ca1bf6fb1c8cb654f1387b65ea1a911b00d59de712fR29-R34) of subcommands, is this sufficient?

Hm, I get 18ms with 69 build-systems, and 3ms with 1 ... should I lazy-load them?

**Comment by Alexey-T** [comment]
it is very easy to change on_init to on_open, lets do it?

**Comment by Alexey-T** [comment]
readme- wrote the reply in GH.
