### ISSUE TITLE
on_init to on_open?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_runner#12]
we dont need to set hotkeys for untitled tabs, but we need it for titled tabs. so on_open is OK place? on_open better -- we make faster Cud call w/o any files.

**Comment by halfbrained** [comment]
moved https://github.com/halfbrained/cuda_runner/commit/b490435a7d0638622a1d5fd243cae5149c020bbf

extra code because `on_open()` is not called when saving untitled tab

**Comment by Alexey-T** [comment]
so on_init is kept? then on_open is not needed. I wanted to replace on_init->on_open, and erase on_init.
can we have on_open + on_save?

**Comment by halfbrained** [comment]
Currently I'm loading build-systems (the slow part) in on_open() or when build-systems are accessed.

1. If I delete on_open() - build-systems will load on first access to them (building something or calling "Choose build config..." command)
2. load build-systems in on_open() + on_save()

Both easy changes, but I'm not sure why second would be preferable.

**Comment by Alexey-T** [comment]
i wanted to avoid runner initing on Cud start w/o any files. can we avoid it? but still have hotkeys working for files?

**Comment by Alexey-T** [comment]
if we make this

- empty dummy on_save (to load plugin after first file save)
- empty dummy on_open (for the same)
- tools/hotkeys are inited in `__init__`

it is OK?

**Comment by halfbrained** [comment]
The problem is that custom subcommands with hotkeys
![hotkey1](https://user-images.githubusercontent.com/74829192/111670402-79479f00-8820-11eb-9c2b-6b8064b986b1.png)

are losing them if plugin is not loaded on start
![hotkey2](https://user-images.githubusercontent.com/74829192/111670801-e9eebb80-8820-11eb-8e45-e6758a5f37b3.png)

**Comment by Alexey-T** [comment]
Ok
