### ISSUE TITLE
suggestion how to install build systems

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_runner#16]
Is it ok way?

- put all b-systems files to SF.net https://sourceforge.net/projects/cudatext/files/addons/buildsystems . Format - usual Cud addon in zip
- publish in Cud registry
- user installs b-systems from AddonManager ~~(from next Cud version) or by downloading zip + opening zip in Cud (works now)~~

![Screenshot from 2021-03-18 01-46-06](https://user-images.githubusercontent.com/4154978/111548430-c0d01b80-878b-11eb-9a3d-815a935adcf2.png)

**Comment by Alexey-T** [comment]
if it is OK, send me all b-systems. how to handle EXE files (or scripts) in them? we may zip them to additional files and add to registry:
```
  "files": "url_of_zip_file_with_scripts",
```
ok?

**Comment by Alexey-T** [comment]
b-systems will have EXE or scripts.
for this, we must change "data/tools" folder to "data/buildsystems/tools".

**Comment by halfbrained** [comment]
installed build-systems from addon manager without problems

"data/buildsystems/tools" was the initial suggestion so already using that

I was testing on C++, and that build-system has wrong file regex for the output I'm getting... so there is probably some fixing in build-systems to be done for the best result

**Comment by halfbrained** [comment]
Screenshot hints at an option to install a single build-system in the future? Because I don't see that now.

**Comment by Alexey-T** [comment]
I want 

- 1 package with most of b-systems
- and: N packages with b-systems with EXE/SH tools
