### ISSUE TITLE
b-system 'Inno setup' gives strange error msg. it's ok?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_runner#21]
![Screenshot from 2021-03-18 16-07-53](https://user-images.githubusercontent.com/4154978/111631178-28c24880-8804-11eb-8a1e-e667f89ddfd6.png)

**Comment by Alexey-T** [comment]
I have NO opened proj in Cud. also good to have-- special message from runner that I must have proj opened!

**Comment by Alexey-T** [comment]
BTW, we can make change in our b-system version. if its hard to support such macros.

**Comment by halfbrained** [comment]
I will add a message about needing a project opened.
I can give an option to assign a custom working directory for the file to used instead of project... or just Project warning is enough?

**Comment by Alexey-T** [comment]
post some warning to Output panel: that project is excepted by tool, but it is not opened.
InnoSetup is simple tool, it must work anyway. after warning

**Comment by halfbrained** [comment]
There are seven build-systems total that use these variables for a work-dir
```
Compass
Homebrew
Inno Setup
NSIS
nsL Assembler
OpenVPN
RSpec - Bundle Exec
```  
they can easily fallback to file directory if no project is opened, but they chose not to, I assumed they had a reason... 

Now that I'm thinking about this, when the build-system is asking for "a project path or an opened directory", it is probably safe to give file's directory in most cases.

I should give a warning and use file's directory in such cases, right?

**Comment by Alexey-T** [comment]
right.

**Comment by halfbrained** [comment]
fixed

**Comment by halfbrained** [comment]
fixed
