### ISSUE TITLE
strange log, 'command' NONE, why?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_runner#26]
![Screenshot from 2021-03-18 21-54-41](https://user-images.githubusercontent.com/4154978/111681837-c2a1e980-8834-11eb-906e-5135bc5aee2c.png)

**Comment by Alexey-T** [comment]
[Free Pascal.zip](https://github.com/halfbrained/cuda_runner/files/6166614/Free.Pascal.zip)
--this is b-system

**Comment by Alexey-T** [comment]
after b-system change, 'command' is filled now! why it was empty?
![Screenshot from 2021-03-18 21-59-23](https://user-images.githubusercontent.com/4154978/111682324-45c33f80-8835-11eb-84c9-4fb9caf1a036.png)

**Comment by halfbrained** [comment]
fixed

log string should have been `-- Command: ${shell_cmd:${cmd}}` instead of `-- Command: ${cmd}`
