### ISSUE TITLE
cannot add value to OS PATH

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_runner#27]
this shows how I add a value to PATH: I use ":" char separator and "$PATH" to get old PATH value and add there my dir.
It dont work!
linker is not found by Freepascal. so PATH is broken for Freepascal.
I tried ";" separator.
I tried "$path;new_dir" too.

![Screenshot from 2021-03-18 23-13-18](https://user-images.githubusercontent.com/4154978/111691798-ba9b7700-883f-11eb-84e6-57e5337f0181.png)

**Comment by Alexey-T** [comment]
now FPC is working ok.
but we cannot append strings to PATH?
```
{
  "file_patterns": ["*.pp", "*.pas"],
  "file_regex": "(.+?)\\((\\d+),(\\d+)\\)\\s(.+)$",
  "working_dir": "$file_path",
  "linux": {
    "cmd": ["/home/user/fpcupdeluxe/fpcupdeluxe32/fpc/bin/x86_64-linux/fpc.sh", "$file_name"],
  }
}
```

**Comment by halfbrained** [comment]
fixed
examples:
```
"path": $path;c:\\mingw\\bin;c:\\mingw\\msys\\1.0\\bin"

"path": /usr/local/bin:$PATH"

"path": /usr/local/bin:/usr/bin:/bin:${path}"
```
