### ISSUE TITLE
allow sections in b-systems for other OSes

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_runner#29]
e.g.
```
  "freebsd": {
     "cmd": ....
  }
```

- freebsd
- openbsd
- netbsd
- dragonflybsd
- solaris

**Comment by Alexey-T** [comment]
https://docs.python.org/3/library/os.html#os.uname
we need some hack of its result: "darwin" -> "osx"
and lower().

```
OS_KEY = os.uname()[0].lower()
if OS_KEY == 'darwin':
    OS_KEY = 'osx'

IS_WIN = OS_KEY=='windows'
IS_MAC = OS_KEY=='osx'
IS_LIN = not IS_WIN and not IS_MAC

```

**Comment by halfbrained** [comment]
from referenced `os.uname` doc:
> Availability: recent flavors of Unix.

indeed on win7 it's missing
![uname](https://user-images.githubusercontent.com/74829192/111768201-4cdb6380-88b0-11eb-9b13-dcc15c574686.png)

works on macos :)

**Comment by halfbrained** [comment]
I'll look into this a bit later

**Comment by Alexey-T** [comment]
```
IS_WIN = os.name=='nt'
IS_MAC = sys.platform=='darwin'
IS_LIN = not IS_WIN and not IS_MAC
OS_KEY = 'windows' if IS_WIN else ('osx' if IS_MAC else os.uname()[0].lower() )
```

**Comment by halfbrained** [comment]
thanks, changed

**Comment by halfbrained** [comment]
Works
`linux` on Ubuntu
`osx` on macos
`windows` on win
`freebsd`
