### ISSUE TITLE
command 'Config' don't work here (lexer Python, no tools for python)

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_runner#3]

**Comment by halfbrained** [comment]
Please elaborate

**Comment by Alexey-T** [comment]
- I start Cud with empty tab or tab wutih Python file
- I call plugin command "Config" and it does nothing! while I need to open the config

**Comment by halfbrained** [comment]
Weird, just checked on fresh install, with empty tab - "Options / Plugins / Runner / Config" opens `.../settings/cuda_runner.json`

**Comment by Alexey-T** [comment]
now it's OK.
