### ISSUE TITLE
dont show modal error msg on Json error

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_runner#30]
better show line in console. with prefix 'NOTE:' so Cud shows blue counter for this line.
![Screenshot from 2021-03-19 16-03-02](https://user-images.githubusercontent.com/4154978/111784666-b8cbc500-88cc-11eb-86ec-fe8336ae97f3.png)

**Comment by halfbrained** [comment]
changed https://github.com/halfbrained/cuda_runner/commit/9c1f26eff5eb860c37846327b5e6d39fc5d96231
