### ISSUE TITLE
Maybe move most of 'imports' to a work function

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_runner#39]
on notebook Runner adds 70ms to start. can we move all slow initing to working func?

**Comment by Alexey-T** [comment]
Startup: 330ms, plugins: 60ms (runner 54ms, hilite_occurrences 9ms, lsp 6ms)

@halfbrained Can we 'delay' slow initing?

**Comment by halfbrained** [comment]
Will check it

**Comment by halfbrained** [comment]
improved startup from 31ms to 22ms when it is the only plugin on app start. I'm interest to know how it changed on your end.

(If I remove cudax_lib (`get_translation()`) it drops to 10ms... but I can't delay that in a reasonable way)

**EDIT**: removing other imports gave me almost zero improvement

**Comment by Alexey-T** [comment]
on my end: 69ms-> 48ms

**Comment by Alexey-T** [comment]
maybe even cudax_lib can be improved? or symbol get_translation can be moved to another lib, e.g. name it cudax_i18n , and this lib can be made fast? IDK

**Comment by Alexey-T** [comment]
closing.

**Comment by halfbrained** [comment]
With other plugins now 'runner' starts in 3ms for me, so overall it's probably totally fine

**Comment by Alexey-T** [comment]
here it is 27ms.

**Comment by Alexey-T** [comment]
still 48ms on the slow PC.

**Comment by halfbrained** [comment]
I would be curious to see sometime how fast it will be without i18n
```
from cudax_lib import get_translation
_   = get_translation(__file__)  # I18N
```
for that replace above lines with:
```
_ = lambda s: s
```

**Comment by Alexey-T** [comment]
I tried it, it gave about 10-15ms.

**Comment by Alexey-T** [comment]
no, it gave 26 ms.
