### ISSUE TITLE
OS_KEY var supports only 3 OS, what about others

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_runner#4]

**Comment by Alexey-T** [comment]
and this
```
    OPTIONS = {
        'selector',
        'file_patterns', # :["*.py"]
        'keyfiles',     # files to trigger this build, : ["Makefile"].
        'variants',     # list of subsidiary build systems that will inherit the options from the top-level; has 'name'
        'cancel',
        'target',       # 'Command' to run when the build system is invoked.
    
        'windows',
        'osx',
        'linux',
    }
```

**Comment by halfbrained** [comment]
That is by the [format specification](http://www.sublimetext.com/docs/3/build_systems.html#option-windows) ... if it's not windows or macos - it's a linux.

I suppose it's easy to add more if further distinction is necessary, are commands will be different for other OS's?

**Comment by Alexey-T** [comment]
no, commands will be not different. I ask that it just works on *bsd/ solaris. with 'linux' code. if it does- all ok
