### ISSUE TITLE
Live Output: PHP works, Python not

### ISSUE THREAD

**Issue by TomBraider42** [halfbrained/cuda_runner#40]
With PHP Output line by line every second works:
```
<?php
for($i=0;$i<5;$i++){
	sleep(1);
	echo "$i is here\n";
}
?>
```

```
{
	"cmd": ["php-win", "$file"],
	"selector": "source.php",
	"working_dir": "${project_path:${folder}}",
}
```
With Python Output will show after script finished:
```
import time

def ForTest():
    for i in range(5):
        time.sleep(1)
        print(str(i) + " is here")

if __name__ == '__main__':
    ForTest()
```

```
{
	"cmd": ["pythonw", "$file"],
	"selector": "source.python",
	"working_dir": "${project_path:${folder}}",
}
```

Calling `py test.py` in windows command line works like PHP.
Any Idea?

**Comment by Alexey-T** [comment]
confirmed for Python. on Linux now. all 5 lines appear as 1 chunk. @halfbrained

**Comment by Alexey-T** [comment]
it's Py problem. see here https://www.geeksforgeeks.org/python-sys-stdout-flush/
with `flush()` call it works OK.
