### ISSUE TITLE
why not to have precompiled regex?

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_runner#6]
```
return re.sub('(?<!\\\)(\$[a-z_]+|\$\{[^}]+\}*)', repl, s)
```

**Comment by halfbrained** [comment]
From `re` [doc](https://docs.python.org/3/library/re.html)

> The compiled versions of the most recent patterns passed to re.compile() and the module-level matching functions are cached, so programs that use only a few regular expressions at a time needn’t worry about compiling regular expressions.

**Comment by halfbrained** [comment]
...Oh, nevermind, I'm not sure how that would work with CudaText plugins... will fix it

**Comment by halfbrained** [comment]
fixed
