### ISSUE TITLE
it's not fully correct function

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_runner#8]
```
def collapse_path(path):
    if path.startswith(USER_DIR):
        path = path.replace(USER_DIR, '~', 1)
    return path
```

for name like `/home/user2/test' it gives `~2/test`
:)

**Comment by Alexey-T** [comment]
and for `~` in the middle of name.

**Comment by Alexey-T** [comment]
need
`if (path+'/').startswith(USER_DIR+'/'):`

**Comment by halfbrained** [comment]
Dont leave Windows behind :)
`(path + os.sep).startswith(USER_DIR + os.sep)`

fixed
