### ISSUE TITLE
new readme

### ISSUE THREAD

**Issue by Alexey-T** [halfbrained/cuda_runner#9]
del

**Comment by Alexey-T** [comment]
update
[readme.txt](https://github.com/halfbrained/cuda_runner/files/6159449/readme.txt)

**Comment by halfbrained** [comment]
Thanks, added with some additional info, good? - https://github.com/halfbrained/cuda_runner/blob/main/readme/readme.txt

**Comment by Alexey-T** [comment]
>It is possible to bind hotkey to a specific build command. This can be done by
adding subcommand description to the "subcommands" category in the config. 

- config -- of plugin? of b-system?
- 'category'- what is it? pls some example, fragment of  config (plugin config)

**Comment by halfbrained** [comment]
clarified more https://github.com/halfbrained/cuda_runner/commit/9d4e5675cb1aa48570bfc111512a3375624afce4
